name: "Nix Build"
on:
  push:
    branches: [master]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v6
      - run: nix-build
      - uses: cachix/cachix-action@v3
        with:
          name: rogryza
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
